"""Data models and schemas"""

from app.models.base import Subject, BaseResponse, ErrorResponse
from app.models.content import (
    ContentType,
    DifficultyLevel,
    Topic,
    ContentItem,
    ContentItemCreate,
    ContentChunk,
    PYQ,
    PYQCreate,
    HOTSQuestion,
    HOTSQuestionCreate,
    Video,
    VideoCreate,
    Timestamp,
)
from app.models.progress import (
    MasteryScore,
    Progress,
    ProgressCreate,
    ProgressUpdate,
    Achievement,
    MicroPlan,
    MicroPlanCreate,
    MicroPlanUpdate,
    Quiz,
)
from app.models.exam import (
    ExamQuestion,
    ExamSet,
    ExamSetCreate,
    TestSession,
    TestSessionCreate,
    TestSessionUpdate,
    AnswerSubmission,
    TestResult,
    PerformanceTrend,
)
from app.models.doubt import (
    DoubtType,
    DoubtQuery,
    DoubtQueryCreate,
    WolframStep,
    Source,
    DoubtResponse,
    HomeworkSession,
    HomeworkAttempt,
    HintRequest,
    HintResponse,
)
from app.models.rag import (
    EmbeddingVector,
    RAGQuery,
    RAGContext,
    RAGResponse,
    EmbeddingRequest,
    EmbeddingResponse,
    SimilaritySearchRequest,
    SimilaritySearchResult,
    ContentIndexRequest,
    ContentIndexResponse,
)
from app.models.admin import (
    StudentAlert,
    AdminDashboardMetrics,
    ContentUploadRequest,
    ContentUploadResponse,
    StudentOverview,
    StudentDetailedProfile,
    StudentExportData,
    ContentPreview,
)

__all__ = [
    # Base
    "Subject",
    "BaseResponse",
    "ErrorResponse",
    # Content
    "ContentType",
    "DifficultyLevel",
    "Topic",
    "ContentItem",
    "ContentItemCreate",
    "ContentChunk",
    "PYQ",
    "PYQCreate",
    "HOTSQuestion",
    "HOTSQuestionCreate",
    "Video",
    "VideoCreate",
    "Timestamp",
    # Progress
    "MasteryScore",
    "Progress",
    "ProgressCreate",
    "ProgressUpdate",
    "Achievement",
    "MicroPlan",
    "MicroPlanCreate",
    "MicroPlanUpdate",
    "Quiz",
    # Exam
    "ExamQuestion",
    "ExamSet",
    "ExamSetCreate",
    "TestSession",
    "TestSessionCreate",
    "TestSessionUpdate",
    "AnswerSubmission",
    "TestResult",
    "PerformanceTrend",
    # Doubt
    "DoubtType",
    "DoubtQuery",
    "DoubtQueryCreate",
    "WolframStep",
    "Source",
    "DoubtResponse",
    "HomeworkSession",
    "HomeworkAttempt",
    "HintRequest",
    "HintResponse",
    # RAG
    "EmbeddingVector",
    "RAGQuery",
    "RAGContext",
    "RAGResponse",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "SimilaritySearchRequest",
    "SimilaritySearchResult",
    "ContentIndexRequest",
    "ContentIndexResponse",
    # Admin
    "StudentAlert",
    "AdminDashboardMetrics",
    "ContentUploadRequest",
    "ContentUploadResponse",
    "StudentOverview",
    "StudentDetailedProfile",
    "StudentExportData",
    "ContentPreview",
]
