// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eplwyruyzllqbmnpmdko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbHd5cnV5emxscWJtbnBtZGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3Nzg3NTMsImV4cCI6MjA3OTM1NDc1M30.hlem8AbwvxmFbCyqtCyWnTtxqeiG9qLcggOfXh8GY5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});